### ISSUE TITLE
ClassCastException in DefaultPool#close 

### ISSUE THREAD

**Issue by saket** [caffeine-mgn/pw.binom.io#17]
Trying to call `ByteBufferPool#close()` results in a `ClassCastException`:

```
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lpw.binom.ByteBuffer; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lpw.binom.ByteBuffer; is in unnamed module of loader 'app')
	at pw.binom.ByteBufferPool.close(ByteBuffer.kt:101)
```

I'm not sure why but Kotlin isn't too happy with this line:

https://github.com/caffeine-mgn/pw.binom.io/blob/6797740500fc6bb1dadd8ac1c9ff6bc193963914/core/src/commonMain/kotlin/pw/binom/pool/DefaultPool.kt#L5

I'm curious, can that be changed to `arrayOfNulls<T?>(capacity)`?

**Comment by caffeine-mgn** [comment]
Fixed in 0.1.23
