### ISSUE TITLE
Correct way of reading a file

### ISSUE THREAD

**Issue by saket** [caffeine-mgn/pw.binom.io#18]
The example mentioned in the [README](https://github.com/caffeine-mgn/pw.binom.io/blob/master/file/README.md) looks stale. I found this in your sample app and modified the code a bit:

```kotlin
val buffer = byteBufferPool.borrow()
ByteArrayOutput().use { out ->
  delegate.read().use {
    it.copyTo(out, buffer)
  }
  out.trimToSize()
  out.data.clear()
  return out.data.asUTF8String()
}
```

Question 1: Is this the cleanest way to read files right now? 
Question 2: I found it a bit weird that `Input#copyTo` doesn't recycle borrowed items from the buffer pool. Is this correct?
Question 3: What's the intended way of maintaining a buffer pool? Should it be shared across multiple file reads?

**Comment by caffeine-mgn** [comment]
1. Your code will read all data from file to memory, and then data from memory will convert to UTF-8 string
You can read text from file without read all file to memory using code:
```
File("file.txt").read().reader(Charsets.UTF8).use { 
        it.readText()
    }
```

2. Not it is not correct. Fixed in 0.1.23
3. Yes, you can use same buffer pool for several files. BufferPool is used as provider of temp buffer for into this some data

**Comment by saket** [comment]
Got it, thanks for explaining!

**Comment by saket** [comment]
I just noticed that `readText()` reads one character at a time. Would that not be… slow?

**Comment by saket** [comment]
Do you have any macOS test for that above code snippet? I'm running into this error on my side:

```
kotlin.IllegalStateException
kotlin.IllegalStateException
	at kotlin.Throwable#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Throwable.kt:27)
	at kotlin.Exception#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Exceptions.kt:21)
	at kotlin.RuntimeException#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Exceptions.kt:32)
	at kotlin.IllegalStateException#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Exceptions.kt:68)
	at pw.binom.charset.AbstractIconv#iconv(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/linuxX64Main/kotlin/pw/binom/charset/AbstractIconv.kt:63)
	at pw.binom.charset.IconvCharsetDecoder#decode(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/linuxX64Main/kotlin/pw/binom/charset/IconvCharsetDecoder.kt:10)
	at pw.binom.io.BufferedInputReader.prepareBuffer#internal(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/commonMain/kotlin/pw/binom/io/BufferedInputReader.kt:24)
	at pw.binom.io.BufferedInputReader#read(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/commonMain/kotlin/pw/binom/io/BufferedInputReader.kt:53)
	at pw.binom.io#readText@pw.binom.io.Reader(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/commonMain/kotlin/pw/binom/io/Reader.kt:61)
	at me.saket.press.shared.sync.git.BinomBasedFile#read(/Users/saket/Projects/Press/shared/src/commonMain/kotlin/me/saket/press/shared/sync/git/BinomBasedFile.kt:52)
```

What's weird is that the error stacktrace contains files that are present in `linuxX64Main` whereas I'm running on macOS.

**Comment by caffeine-mgn** [comment]
> I just noticed that `readText()` reads one character at a time. Would that not be… slow?

In 0.1.23 I will add special methods to `AsyncBufferedInputReader`/`BufferedInputReader` for they are can returns line and all text

**Comment by caffeine-mgn** [comment]
> Do you have any macOS test for that above code snippet? I'm running into this error on my side:
> 
> ```
> kotlin.IllegalStateException
> kotlin.IllegalStateException
> 	at kotlin.Throwable#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Throwable.kt:27)
> 	at kotlin.Exception#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Exceptions.kt:21)
> 	at kotlin.RuntimeException#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Exceptions.kt:32)
> 	at kotlin.IllegalStateException#<init>(/Users/teamcity/buildAgent/work/cae0e6559deed4c4/runtime/src/main/kotlin/kotlin/Exceptions.kt:68)
> 	at pw.binom.charset.AbstractIconv#iconv(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/linuxX64Main/kotlin/pw/binom/charset/AbstractIconv.kt:63)
> 	at pw.binom.charset.IconvCharsetDecoder#decode(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/linuxX64Main/kotlin/pw/binom/charset/IconvCharsetDecoder.kt:10)
> 	at pw.binom.io.BufferedInputReader.prepareBuffer#internal(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/commonMain/kotlin/pw/binom/io/BufferedInputReader.kt:24)
> 	at pw.binom.io.BufferedInputReader#read(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/commonMain/kotlin/pw/binom/io/BufferedInputReader.kt:53)
> 	at pw.binom.io#readText@pw.binom.io.Reader(/Users/runner/work/pw.binom.io/pw.binom.io/core/src/commonMain/kotlin/pw/binom/io/Reader.kt:61)
> 	at me.saket.press.shared.sync.git.BinomBasedFile#read(/Users/saket/Projects/Press/shared/src/commonMain/kotlin/me/saket/press/shared/sync/git/BinomBasedFile.kt:52)
> ```
> 
> What's weird is that the error stacktrace contains files that are present in `linuxX64Main` whereas I'm running on macOS.

Can you attach your file and tell charset of the file?

**Comment by saket** [comment]
> In 0.1.23 I will add special methods to AsyncBufferedInputReader/BufferedInputReader for they are can returns line and all text

Sounds good!

> Can you attach your file and tell charset of the file?

Here you go: https://github.com/saket/press/blob/29c57577d70d01b90f6a3dd26bae08f4267ddc84/shared/src/commonTest/kotlin/me/saket/press/shared/sync/git/FileCanaryTests.kt#L28-L32

Implementation of `File` using your library: https://github.com/saket/press/blob/saket/oct28/fix-failing-tests/shared/src/commonMain/kotlin/me/saket/press/shared/sync/git/BinomBasedFile.kt

**Comment by caffeine-mgn** [comment]
I can't find your file `BinomBasedFile.kt` :(
