### ISSUE TITLE
Cannot download library

### ISSUE THREAD

**Issue by dragossusi** [caffeine-mgn/pw.binom.io#6]
I deleted my old files and now it can't find it, i used 0.1.16, changed to 0.1.17 but it still says:

```Could not resolve pw.binom.io:file:0.1.17.```

**Comment by dragossusi** [comment]
Looks like you removed macos targets, that's why i was getting errors

**Comment by caffeine-mgn** [comment]
I don't have any mac for build mac.

**Comment by caffeine-mgn** [comment]
Try again use pw.binom.io:file:0.1.17

**Comment by dragossusi** [comment]
I can help with building for macos/ios

**Comment by caffeine-mgn** [comment]
I think it is very large work. Need implement working with FileSystem, Network. I want to reimplement working with network, 
in particular method `connect`. It is must be async.

Soon I will get macos device, and then I can implement it all.

**Comment by dragossusi** [comment]
Hello @caffeine-mgn ,

I cannot download version 0.1.18.

**Comment by dragossusi** [comment]
https://repo.binom.pw/releases/pw/binom/io/file

**Comment by saket** [comment]
I think this issue can now be closed?

**Comment by caffeine-mgn** [comment]
@saket, yes, you right

Fixed in 0.1.22
