### ISSUE TITLE
Kotlin 1.4

### ISSUE THREAD

**Issue by saket** [caffeine-mgn/pw.binom.io#9]
Just came across this project while trying to write my own implementation for file access across platforms, this looks simple and great! Are there any plans for releasing `v0.1.8` with kotlin 1.4 soon?

**Comment by caffeine-mgn** [comment]
Yes. 0.1.18 will be using Kotlin 1.4
I try to finish on Monday. Also, I will try to add the OpenSSL compilation functionality during the compilation of the library instead of adding the C headers and the compiled static library.

**Comment by saket** [comment]
Awesome. Are there any plans of splitting the modules into separate libraries? I'm assuming the answer is no, but I was thinking that it'll be easier for people to contribute. As someone who's new to kotlin multiplatform, I'd feel overwhelmed by this project.

**Comment by caffeine-mgn** [comment]
I didn't plan on breaking the project. This makes it more convenient to maintain a common version for the entire project.
